// 數值／門檻／時限題庫（甲級學科常考：幾小時、幾人、幾公尺、濃度分貝等）
// numeric: true 供抽題加權

export const NUMERIC_MC_POOL = [
  {
    topic: "法規",
    text: "事業單位僱用勞工達多少人以上，應置勞工安全衛生業務主管？",
    options: ["10 人", "30 人", "50 人", "100 人"],
    answer: 1,
    explain: "三十人以上應置業務主管；常與五十人（健康服務）、一百人（委員會）混淆。",
    source: "《職業安全衛生管理辦法》",
    hard: true,
    trap: true,
    numeric: true,
  },
  {
    topic: "法規",
    text: "事業單位僱用勞工達多少人以上，應設置職業安全衛生委員會？",
    options: ["30 人", "50 人", "100 人", "300 人"],
    answer: 2,
    explain: "一百人以上應設委員會，且依法至少每月開會一次。",
    source: "《職業安全衛生法》第30條",
    hard: true,
    numeric: true,
  },
  {
    topic: "法規",
    text: "事業單位僱用勞工達多少人以上，應置職業安全衛生管理師？",
    options: ["100 人", "200 人", "300 人", "500 人"],
    answer: 2,
    explain: "三百人以上應置管理師一人；規模更大者編制另依辦法。",
    source: "《職業安全衛生管理辦法》",
    hard: true,
    trap: true,
    numeric: true,
  },
  {
    topic: "115年修法",
    text: "修正後職安法，事業單位僱用勞工達多少人以上，應置勞工健康服務人員或委託專業機構？",
    options: ["30 人", "50 人", "100 人", "300 人"],
    answer: 1,
    explain: "115 年修法：五十人以上應置健康服務人員或委託機構。",
    source: "《職業安全衛生法》第22條",
    hard: true,
    law2026: true,
    numeric: true,
  },
  {
    topic: "115年修法",
    text: "雇主僱用勞工達多少人以上，應訂定職場霸凌「申訴管道」並公開揭示？",
    options: ["5 人", "10 人", "30 人", "50 人"],
    answer: 1,
    explain: "十人以上訂申訴管道；三十人以上另須防治措施及懲處規範。",
    source: "《職業安全衛生法》第22條之一",
    law2026: true,
    numeric: true,
  },
  {
    topic: "115年修法",
    text: "雇主僱用勞工達多少人以上，應訂定職場霸凌防治措施、申訴及懲處規範？",
    options: ["10 人", "30 人", "50 人", "100 人"],
    answer: 1,
    explain: "三十人門檻訂定完整防治、申訴、懲處規範。",
    source: "《職業安全衛生法》第22條之一",
    law2026: true,
    numeric: true,
  },
  {
    topic: "職業安全衛生法",
    text: "發生死亡職業災害，事業單位應於多少小時內通報勞動檢查機構？",
    options: ["1 小時", "8 小時", "24 小時", "48 小時"],
    answer: 1,
    explain: "死亡災害 8 小時內通報；受傷或疾病為 24 小時。",
    source: "《職業安全衛生法》第26條",
    hard: true,
    trap: true,
    numeric: true,
  },
  {
    topic: "職業安全衛生法",
    text: "發生受傷或疾病之職業災害，事業單位應於多少小時內通報？",
    options: ["8 小時", "24 小時", "48 小時", "72 小時"],
    answer: 1,
    explain: "受傷或疾病 24 小時內通報，勿與死亡 8 小時混淆。",
    source: "《職業安全衛生法》第26條",
    hard: true,
    trap: true,
    numeric: true,
  },
  {
    topic: "墜落災害",
    text: "勞工於高度多少以上之處所作業，雇主應設置護欄、安全網或使勞工使用安全帶？",
    options: ["1 公尺", "1.5 公尺", "2 公尺", "3 公尺"],
    answer: 2,
    explain: "二公尺以上高處作業須採防墜措施，為設施規則常考數值。",
    source: "《職業安全衛生設施規則》第238條",
    hard: true,
    numeric: true,
  },
  {
    topic: "專業課程",
    text: "局限空間作業，空氣中氧氣濃度應維持在下列何者範圍？",
    options: ["18.0%～25.0%", "19.5%～23.5%", "20.0%～22.0%", "16.0%～19.5%"],
    answer: 1,
    explain: "氧氣濃度 19.5%～23.5% 為常見安全作業範圍；低於 19.5% 有缺氧危害。",
    source: "《職業安全衛生設施規則》局限空間作業",
    hard: true,
    trap: true,
    numeric: true,
  },
  {
    topic: "專業課程",
    text: "局限空間作業，氧氣濃度低於多少時，不得勞工進入作業？",
    options: ["19.5%", "18.0%", "16.0%", "23.5%"],
    answer: 0,
    explain: "低於 19.5% 屬缺氧環境，不得進入從事作業。",
    source: "《職業安全衛生設施規則》",
    hard: true,
    numeric: true,
  },
  {
    topic: "專業課程",
    text: "八小時日加權平均噪音暴露量達多少 dBA 以上，屬第一級噪音作業管理範圍（概念）？",
    options: ["80 dBA", "85 dBA", "90 dBA", "100 dBA"],
    answer: 1,
    explain: "85 dBA 為常見分級門檻起點；90 dBA 以上須採更嚴格措施。",
    source: "《職業安全衛生設施規則》噪音作業",
    hard: true,
    numeric: true,
  },
  {
    topic: "專業課程",
    text: "八小時日加權平均噪音暴露量達 90 dBA 以上之作業場所，雇主應使勞工佩戴？",
    options: ["一般棉口罩", "防噪音耳罩或耳塞", "安全帽即可", "不必任何防護"],
    answer: 1,
    explain: "90 dBA 以上須採工程管理措施並使勞工佩戴 hearing PPE。",
    source: "《職業安全衛生設施規則》",
    hard: true,
    numeric: true,
  },
  {
    topic: "法規",
    text: "職業安全衛生委員會依法至少多久開會一次？",
    options: ["每週", "每月", "每季", "每年"],
    answer: 1,
    explain: "每月至少開會一次，與「每季」為常見混淆選項。",
    source: "《職業安全衛生法》第32條",
    hard: true,
    trap: true,
    numeric: true,
  },
  {
    topic: "學科題型",
    text: "甲級學科測驗時間為多少分鐘？",
    options: ["60 分鐘", "80 分鐘", "100 分鐘", "120 分鐘"],
    answer: 2,
    explain: "學科 100 分鐘；80 題、60 分及格。",
    hard: true,
    numeric: true,
  },
  {
    topic: "學科題型",
    text: "甲級學科測驗及格分數為多少分（滿分 100）？",
    options: ["50 分", "60 分", "70 分", "80 分"],
    answer: 1,
    explain: "學科、術科皆 60 分及格。",
    numeric: true,
  },
  {
    topic: "學科題型",
    text: "甲級學科複選題共幾題、每題幾分？",
    options: ["10 題、每題 2 分", "20 題、每題 2 分", "20 題、每題 1 分", "30 題、每題 2 分"],
    answer: 1,
    explain: "20 複選 × 2 分 = 40 分；60 單選 × 1 分 = 60 分。",
    hard: true,
    numeric: true,
  },
  {
    topic: "共同科目",
    text: "107 年起，四項共同科目於各職類學科抽題比例各占多少？",
    options: ["各 5%", "各 10%", "各 20%", "各 25%"],
    answer: 0,
    explain: "四項共同科目各 5%，合計約 20%；甲級各科目約 4 題。",
    source: "技能檢定中心公告",
    hard: true,
    numeric: true,
  },
  {
    topic: "115年修法",
    text: "職場霸凌向主管機關申訴，自霸凌行為終了起逾幾年不予受理？",
    options: ["1 年", "2 年", "3 年", "5 年"],
    answer: 2,
    explain: "自終了起逾 3 年不受理；在職者離職後 1 年內仍得申訴。",
    source: "《職業安全衛生法》第22條之三",
    law2026: true,
    hard: true,
    numeric: true,
  },
  {
    topic: "115年修法",
    text: "職場霸凌申訴，勞工離職後仍得向主管機關申訴之期限為？",
    options: ["3 個月", "6 個月", "1 年", "3 年"],
    answer: 2,
    explain: "離職之日起 1 年內仍得申訴（但有較長期限規定者從其規定）。",
    source: "《職業安全衛生法》第22條之三",
    law2026: true,
    numeric: true,
  },
  {
    topic: "115年修法",
    text: "職場霸凌調查小組外聘成員比例，不得少於？",
    options: ["四分之一", "三分之一", "二分之一", "三分之二"],
    answer: 2,
    explain: "外聘成員不得少於二分之一，確保調查公正。",
    source: "《職業安全衛生法》第22條之二",
    law2026: true,
    numeric: true,
  },
  {
    topic: "作業環境",
    text: "作業環境監測，粉塵八小時日加權平均容許濃度依何者判定？",
    options: ["勞工自認", "中央主管機關訂定標準", "雇主口頭規定", "同業平均"],
    answer: 1,
    explain: "容許濃度依中央主管機關公告標準；超標須改善。",
    hard: true,
    numeric: true,
  },
  {
    topic: "專業課程",
    text: "高溫作業，濕球溫度達攝氏多少度以上，雇主應使勞工適當休息（常見標準）？",
    options: ["28°C", "30°C", "32°C", "35°C"],
    answer: 2,
    explain: "濕球 32°C 以上為高溫作業常見分級；應調整作息、通風、飲水等。",
    source: "《職業安全衛生設施規則》高溫作業",
    hard: true,
    numeric: true,
  },
  {
    topic: "專業課程",
    text: "可燃性氣體爆炸下限（LEL）數值愈低，通常表示？",
    options: ["愈難燃爆", "愈易達燃爆濃度", "與燃爆無關", "表示最高溫度"],
    answer: 1,
    explain: "LEL 愈低表示較低濃度即可燃爆，較危險。",
    hard: true,
    numeric: true,
  },
  {
    topic: "法規",
    text: "下列人數門檻配對，何者「錯誤」？",
    options: ["30 人—業務主管", "100 人—職安衛委員會", "50 人—置管理師", "300 人—置管理師"],
    answer: 2,
    explain: "50 人為健康服務人員門檻（115 修法）；管理師為 300 人。",
    hard: true,
    trap: true,
    numeric: true,
  },
];

export const NUMERIC_MS_POOL = [
  {
    topic: "法規",
    text: "下列關於「人數門檻」的敘述，何者正確？",
    options: ["30 人以上應置業務主管", "100 人以上應設職安衛委員會", "300 人以上應置管理師", "50 人以上應置管理師"],
    answer: [0, 1, 2],
    explain: "30／100／300 為常考組合；50 人為健康服務（115 修法）非管理師。",
    hard: true,
    trap: true,
    numeric: true,
  },
  {
    topic: "職業安全衛生法",
    text: "職業災害通報時限，下列配對何者正確？",
    options: ["死亡：8 小時內", "受傷或疾病：24 小時內", "所有災害：8 小時內", "僅死亡須通報"],
    answer: [0, 1],
    explain: "死亡 8 小時、受傷 24 小時；「全部 8 小時」為陷阱。",
    hard: true,
    trap: true,
    numeric: true,
  },
  {
    topic: "115年修法",
    text: "115 年修法職場霸凌防治，與「人數」相關之義務包括？",
    options: ["10 人以上訂申訴管道", "30 人以上訂防治及懲處規範", "5 人以上即可免訂規範", "僅 100 人以上適用"],
    answer: [0, 1],
    explain: "10 人申訴管道、30 人完整規範；非僅大企業適用。",
    law2026: true,
    numeric: true,
  },
  {
    topic: "115年修法",
    text: "115 年修法，50 人以上事業單位雇主應？",
    options: ["置勞工健康服務人員或委託機構", "辦理健康管理與職業病預防", "僅一般體檢即可", "勞工自費健康檢查"],
    answer: [0, 1],
    explain: "50 人以上須健康服務編制；非一般體檢可取代。",
    law2026: true,
    numeric: true,
  },
  {
    topic: "專業課程",
    text: "局限空間作業前檢測，氧氣濃度相關正確敘述？",
    options: ["應維持在 19.5%～23.5%", "低於 19.5% 不得進入", "僅入場前測一次即可全程免測", "檢測後不必再測"],
    answer: [0, 1],
    explain: "19.5%～23.5% 為安全範圍；作業中仍須持續或定期再測。",
    hard: true,
    trap: true,
    numeric: true,
  },
  {
    topic: "專業課程",
    text: "高處作業「2 公尺」相關正確敘述？",
    options: ["應設護欄、安全網或使用安全帶", "僅戴安全帽即可", "1 公尺以上即同標準", "2 公尺以下完全不必防護"],
    answer: [0],
    explain: "2 公尺以上須防墜；安全帽不能取代。",
    hard: true,
    numeric: true,
  },
  {
    topic: "學科題型",
    text: "甲級學科測驗數值規格，下列何者正確？",
    options: ["80 題", "60 單選每題 1 分", "20 複選每題 2 分", "100 分鐘", "70 分及格"],
    answer: [0, 1, 2, 3],
    explain: "80 題、100 分鐘、60 分及格；非 70 分。",
    hard: true,
    numeric: true,
  },
  {
    topic: "115年修法",
    text: "職場霸凌向主管機關申訴時效，下列何者正確？",
    options: ["自行為終了逾 3 年不受理", "在職者離職後 1 年內仍得申訴", "隨時申訴均不受限", "僅當場申訴"],
    answer: [0, 1],
    explain: "3 年及離職 1 年為修法重點數字。",
    law2026: true,
    trap: true,
    numeric: true,
  },
  {
    topic: "專業課程",
    text: "噪音作業 85 dBA 與 90 dBA 相關正確概念？",
    options: ["85 dBA 起須分級管理", "90 dBA 以上須使勞工佩戴防噪音護具", "85 dBA 以下完全不必管理", "僅發耳塞即可取代工程改善"],
    answer: [0, 1],
    explain: "分級管理；90 dBA 以上須 PPE；不能僅靠耳塞取代工程控制。",
    hard: true,
    numeric: true,
  },
  {
    topic: "法規",
    text: "職安衛委員會會議頻率與組成，下列何者正確？",
    options: ["至少每月開會一次", "勞方代表由勞工推派", "雇主可指定勞方代表", "每季一次即可"],
    answer: [0, 1],
    explain: "每月至少一次；勞方代表不得雇主指定。",
    hard: true,
    trap: true,
    numeric: true,
  },
];
