name = "osh-quiz"
compatibility_date = "2024-09-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "osh-quiz-db"
database_id = "f7e3580f-f693-4802-a6df-169aca7fdaf4"
migrations_dir = "migrations"
